refactor: move from io/ioutil to io and os packages
convox/rack pull request #3582
Opened 2022-09-16 09:20 UTC by Juneezee

The `io/ioutil` package has been deprecated in Go 1.16 (See https://pkg.go.dev/io/ioutil). This PR replaces the existing `io/ioutil` functions with their new definitions in `io` and `os` packages.

- `ioutil.Discard` => `io.Discard`
- `ioutil.NopCloser` => `io.NopCloser`
- `ioutil.ReadAll` => `io.ReadAll`
- `ioutil.ReadDir` => `os.ReadDir` (returns a slice of `os.DirEntry` rather than a slice of `fs.FileInfo`)
- `ioutil.ReadFile` => `os.ReadFile`
- `ioutil.TempDir` => `os.MkdirTemp`
- `ioutil.TempFile` => `os.CreateTemp`
- `ioutil.WriteFile` => `os.WriteFile`

2022-09-20 15:01 UTC, heronrs commented
Thanks for the PR @Juneezee ! We'll merge as soon as we can

2022-09-27 19:56 UTC, Twsouza requested changes
Thanks for submitting the PR, can you take a look at this error?

```
pkg/manifest1/service.go:9:2: imported and not used: "io/ioutil"
```

2022-09-28 13:21 UTC, Twsouza approved these changes
LGTM

2022-09-28 17:37 UTC, heronrs approved these changes

2022-09-29 12:57 UTC, nightfury1204 approved these changes

2022-09-29 22:32 UTC, closed without merging