Store rack install & rack update telemetry data (V2)
convox/rack pull request #3668
Opened 2023-04-25 14:15 UTC by yuriadams

### What is the feature/fix?
![Screenshot 2023-04-25 at 11 14 26](https://user-images.githubusercontent.com/759623/234304722-24209b72-d129-45bd-8d1e-0756b6554021.png)

### Add screenshot or video (optional)

Doc: https://convox602-my.sharepoint.com/:w:/g/personal/yuri_adams_convox_com/ERKCC87MHOxLi6_3F8PqWqIBOWecg2nEg06tIbl9NA6ujQ?e=8bW5AX

### Does it has a breaking change?

No

2023-05-02 18:08 UTC, Twsouza approved these changes

2023-05-08 17:56 UTC, Twsouza requested changes

2023-05-08 18:26 UTC, yuriadams commented on provider/aws/telemetry.go
> +	redactedParams = strings.Join([]string{
@ntner @ddoc, should keep all string params redacted or is it worth do not redacted this list?

2023-05-08 18:48 UTC, Twsouza commented on provider/aws/telemetry.go
> +	redactedParams = strings.Join([]string{
although they are string, they are a list of values or just numbers.

2023-05-10 21:09 UTC, closed without merging